title: Alec Combe # your name (or website title) here
logo: "/images/wut.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Currently a full time student at Weber State University; working towards a bachelors in computer science.
  <br><br>
   
  <br><br>
  <a href="https://www.linkedin.com/in/alec-combe-88414b140/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
